### ISSUE TITLE
操作系统及编译器版本

### ISSUE THREAD

**Issue by Second222None** [openeuler-mirror/etmem#1]
etMem适用的Linux发行版有哪些？有没有推荐的系统版本和编译器版本？谢谢！
另外etMem是位于内核态吗？还是需要内核态与用户态配合使用？系统中的三个engine(slide、cslide、thireparty)的区别是什么？enging是位于用户态还是内核态？期待回复！！！谢谢！！！

**Comment by Yikun** [comment]
Hi, this is only a mirror repo, pls see raise issue in https://gitee.com/src-openeuler/etmem/issues

**Comment by Second222None** [comment]
> 

u can speak Chinese!!! All documents about etMem are in Chinese!!!
